### ISSUE TITLE
after updating visonicinterface to ESPHome 2023.4 - panel does not connect

### ISSUE THREAD

**Issue by EyalRotem** [davesmeghead/visonic#77] opened 2023-04-20 17:42 UTC
Hi,

ISSUE: panel not connecting after updating the visonicinterface to version 2023.4

THINGS I TRIED: this happened before, but a reset to HA usually fixed it (or a reset to the D1mini and reloading the integration). unfortunately - this time, nothing helped.

POSSIBLE CAUSE: a breaking change in the ESPHome - regarding UART devices. this is the [changelog](https://esphome.io/changelog/2023.4.0.html), and this is the issue that is linked to the [breaking change](https://github.com/esphome/esphome/pull/4446).

FIX FOR NOW: restored an older version of HA with the previous ESPHome version - 2023.3.2. after a reboot, everything is working as it should.

LOGS: sorry, i restored and have nothing.  but when i looked (after adding the logger debug stuff in configuration.yaml) there wasn't anything that "screams"  an issue, just failure to connect- if needed - i can update again to replicate the issue, but i rather not, if possible haha.
what i can remember is this is the last line that was the same - and after it, other lines that to not match the working log:
`[custom_components.visonic.pyvisonic] Setting TCP socket Options`

Let me know if I can help.

**Comment by konradwalsh** [comment] 2023-04-21 10:04
I can confirm the same behaviour 

This error originated from a custom integration.

Logger: custom_components.visonic.client
Source: custom_components/visonic/client.py:1185
Integration: Visonic Intruder Alarm (documentation, issues)
First occurred: 11:04:32 (1 occurrences)
Last logged: 11:04:32

Failed to connect into Visonic Alarm. Check Settings.

**Comment by davesmeghead** [comment] 2023-04-21 15:00
I should have added, I have updated to the latest ESPHome and my development connection my PowerMaster 30 works.

**Comment by EyalRotem** [comment] 2023-04-21 17:15
OK, so i have updated to the latest  visonic.yaml when it was last changed.
only thing i changed in it are commenting the "service" and "switch" as i have no need in the triggers and siren. I did try a re-flash previously with no avail.

I will try to find the time to update again - and produce the logs with as much info as possible.

to add info on my setup - it's a powermax 10.

**Comment by davesmeghead** [comment] 2023-04-21 19:44
When you create a log file, remember to set debug for this integration as per [here](https://github.com/davesmeghead/visonic/wiki#logger-settings)

**Comment by EyalRotem** [comment] 2023-04-23 17:30
hi, just finished collecting logs:

here's a [good one](https://pastebin.com/E2TFTs3u) with esphome 2023.3.2.

here's a [bad one ](https://pastebin.com/bUMnNf3N) after updating the d1 mini to esphome 2023.4.

**Comment by davesmeghead** [comment] 2023-04-24 07:49
I'll just add this as well though, in both bad and good log files they both join to and interact with the panel so you should not have seen the ```Failed to connect into Visonic Alarm. Check Settings.``` message.

Can you please confirm whether the "bad" log file failed to bring up the alarm control and sensors in the HA frontend?

**Comment by EyalRotem** [comment] 2023-04-24 08:45
> I'll just add this as well though, in both bad and good log files they both join to and interact with the panel so you should not have seen the `Failed to connect into Visonic Alarm. Check Settings.` message.
> 
> Can you please confirm whether the "bad" log file failed to bring up the alarm control and sensors in the HA frontend?

I can confirm that during the “bad” log, no matter what combination of resetting I tried, it just never connected to the panel, no standard mode, no powerlink, nothing worked.


Than, with just installing the older esphome on the d1mini- it started to work as previously.

later today I’ll try the changes you mentioned.

**Comment by EyalRotem** [comment] 2023-04-24 08:46
> I can confirm that making those changes worked AFTER a full reboot and not just a restart HA

You changed the py files and it worked?
It may be helpful if you can produce logs as well! Thanks for pitching in 🤙🏼

**Comment by konradwalsh** [comment] 2023-04-24 08:50
Here is my log... 
[home-assistant_2023-04-24T08-49-43.095Z.log](https://github.com/davesmeghead/visonic/files/11308473/home-assistant_2023-04-24T08-49-43.095Z.log)

**Comment by konradwalsh** [comment] 2023-04-24 11:42
hmm.. based on yourinfo.. I went back and edited the .py file and restored the MSG_ALIVE2

and now everything works.

The key difference is ESPHOME was updated to a newer version since all of this started.

**Comment by davesmeghead** [comment] 2023-04-24 16:55
@konradwalsh 
Looking through your log file, it disconnects and reconnects back to the panel many times. 
In lines 886 to 887 there is no response from the panel when the "Get Bypass Status" message (line 886) is sent to the panel (although there is no guarantee that the message got to the panel).  
In fact after line 886 to 951 the integration sends many messages to the panel with no response.  
On line 952 your operating system (on whatever hardware you have) declares that the Ethernet connection has been terminated. There is no evidence that your automation did this. This means I think that you have a problem with your network or the ESPHome device. Having said that, because of the sequencing of the messages to the log file by HA, it can be difficult to determine.
On line 980 the integration attempts to reconnect to the panel and succeeds.  
That is until line 1021 where the reconnect service is called (do you have an automation that does this), just as it started to download the EPROM.   
At line 1049 where the reconnect service is called again.
Can you please disable all the HA restart automation that you have and let it do its own thing, then recapture a log file please.

@EyalRotem 
All 3 log files look OK. Each gets to Standard Plus mode but the log files aren't long enough to see if they get to PowerLink mode. 
You're using panel number 1 instead of the default 0, that's all I noticed.  If your front end GUI devices (widgets / icons etc) expect panel 0 sensor names then it may look like the panel hasn't connected when it really has.
Also, I did notice this in your last log file (I think)
```
2023-04-24 14:19:12.147 ERROR (MainThread) [homeassistant.util.logging] Exception in setup_update_entity when dispatching 'esphome_1034ce64b157d501b983a18e43c89fde_on_device_update': ()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/esphome/update.py", line 56, in setup_update_entity
async_add_entities([ESPHomeUpdateEntity(entry_data, dashboard)])
File "/usr/src/homeassistant/homeassistant/components/esphome/update.py", line 90, in __init__
if coordinator.supports_update and not self._device_info.has_deep_sleep:
File "/usr/src/homeassistant/homeassistant/components/esphome/dashboard.py", line 91, in supports_update
raise RuntimeError("Data needs to be loaded first")
RuntimeError: Data needs to be loaded first
```
This seems to be an ESPHome error but I don't know what it means.

**Comment by davesmeghead** [comment] 2023-04-29 09:32
To change the panel number you'd need to delete the integration out of HA, and then add it again, with the panel number set to 0.  If that doesn't work then dleete it, remove all traces of visonic from the HA config files and then add it again.  However, if you're happy with it set to panel 1 then just leave it as is :)

**Comment by EyalRotem** [comment] 2023-04-29 10:45
> To change the panel number you'd need to delete the integration out of HA, and then add it again, with the panel number set to 0. If that doesn't work then delete it, remove all traces of visonic from the HA config files and then add it again. However, if you're happy with it set to panel 1 then just leave it as is :)

ok thanks, it doesn't really matter to me if it doesn't effect the usage =] .
if we're on the  topic of the logs here, might I slip in another question? how can I remove from the UI the "night mode"? is it something from the integration, or from lovelace and UI from HA?
![image](https://user-images.githubusercontent.com/12516268/235298616-8f0f929c-8fd1-4b1d-a518-51fbcd65f602.png)

**Comment by davesmeghead** [comment] 2023-04-30 05:06
It's that good of an idea that I've uploaded version 0.8.4.2 to github.  I have not made it a HACS release yet though so to try it you'll need to download the zip file from Github and unzip it to replace the files if you know how to do this.

It wasn't really necessary until HA have implemented that panel as the GUI panel you need to manually select which buttons are shown by editing the dashboard.

There are 2 new Configuration settings to enable/disable Home and Night. If you give it a try and let me know if you think it's OK.

**Comment by EyalRotem** [comment] 2023-04-30 18:15
Works fine for me!

but I did find a mistyped 'f' I think in the client.py file:
![image](https://user-images.githubusercontent.com/12516268/235369449-a1135c12-8f98-4a58-a866-942bc157913f.png)

**Comment by EyalRotem** [comment] 2023-05-01 08:08
Oh cool, it looked odd since the last version didn’t had it and the first word after it coincidently started with an ‘f’ as well 😅

it looks similar to what ‘$’ does in c# which I’m more familiar with.

**Comment by vettronics** [comment] 2023-05-04 08:05
Hi guys,
Today i updated ESPHome to 2023.4 and had the connection problem.
I have rolled back to previous ESPHome version and its working again.
My question is: will new version  0.8.4.2 fix this problem or do we still have to wait for ESPHome changes?

**Comment by EyalRotem** [comment] 2023-05-04 08:17
As of now-I’m on 2023.4.3 even, and don’t have the issues.
If you can provide logs as Dave requested it might help.
I was unable to reproduce it.

something I and @konradwalsh  did that might helped- is a full restart of the home assistant machine/operating system.

0.8.4.2 will only add a way to disable alarm type in the GUI AS presented in a previous reply (or maybe some more other stuff- that’s up to dave🤗)

**Comment by davesmeghead** [comment] 2023-05-04 21:10
If the integration worked with an old version of ESPHome and doesn't wotk with a new version of ESPHome then the first place to look is ESPHome. So it could either be the ESPHome yaml file that I have on the wiki or something within ESPHome itself.  As I haven't changed the yaml file (and I assume neither have you) then is must be ESPHome itself.  I would assume that new versions of ESPHome should be backwards compatible but sometimes they are not.

So the first place to check is ESPHome itself.  After you update, as @EyalRotem suggested, try restarting everything!  Including the Wemos (or other gadget) on which you have installed ESPHome.  After you updated ESPHome to the new version, did you reinstall the yaml config to the Wemos? 

Although 0.8.4.0 made many changes to the HA Event mechanisms, release 0.8.4.0 up to and including 0.8.4.3 would not have prevented ESPHome from working.

**Comment by vettronics** [comment] 2023-05-04 22:36
After the update, I rebooted both HA machine and the ESP8266 that is connected to the panel with no success...
The log I get from selecting "enable debug logging" on the visonic integration comes with all kind of gibberish from other integrations. Is this the one needed?

**Comment by EyalRotem** [comment] 2023-05-05 04:08
> After the update, I rebooted both HA machine and the ESP8266 that is connected to the panel with no success...
> The log I get from selecting "enable debug logging" on the visonic integration comes with all kind of gibberish from other integrations. Is this the one needed?

You might need to change this temporarily: https://github.com/davesmeghead/visonic/wiki#logger-settings

**Comment by isablend** [comment] 2023-05-05 11:04
This week I updated ESPHome on the D1Mini to 2023.4.4 as well as HA to 2023.5.0 and experienced the same loss of connectivity.   Based on notes from the issue raised I tried a combination of various restores to earlier versions and I could only get it working again with (HA) 2023.4.5 and (ESpHome) 2023.3.2.   I did try just downgrading ESPHome, but that wasn't sufficient and I did try full reboots between restores.   So for me at least it seems to be a combination of HA and ESPHome causing the issue.   I'll post these notes on the issues also.

**Comment by EyalRotem** [comment] 2023-05-05 11:09
> This week I updated ESPHome on the D1Mini to 2023.4.4 as well as HA to 2023.5.0 and experienced the same loss of connectivity. Based on notes from the issue raised I tried a combination of various restores to earlier versions and I could only get it working again with (HA) 2023.4.5 and (ESpHome) 2023.3.2. I did try just downgrading ESPHome, but that wasn't sufficient and I did try full reboots between restores. So for me at least it seems to be a combination of HA and ESPHome causing the issue.

since i cannot reproduce the issue as it "fixed itself", you might wanna try updating again and producing logs - this might help dave find the issue.
when i tried moving between versions, and restarting and all - it just fixed itself.
I'm on HA 2023.5.1 + ESPHome 2023.4.3 now and everything is working as it should

**Comment by EyalRotem** [comment] 2023-05-05 15:57
Weird huh? At least it’s working 😅

**Comment by EyalRotem** [comment] 2023-05-05 15:59
So try and update, see how it goes, like I said, I walked a similar path and it just worked

**Comment by HumanSkunk** [comment] 2023-05-08 07:40
I am also having a similar issue where the system going unavailable within HA. I have managed to get to the latest release of ESPHome 2023.4.4 and it still communicates with the Alarm. I am running HA at 2023.4.6 and all works. Soon as I migrate the Addon from 8.2.4 then it just wont connect and I get the amber exclamation mark on the alarm panel and all entities reporting at unavailable. I have tried restarting and rebooting HA and there is no difference. The only way I can them to communicate again is through restoring the update prior to updating the Addon. I will try again in a couple of days with debug logging turned on to see what is going on. There is no issue with ESPHome as it works with the latest release.

One thing I did notice in comparing the yaml file on the D1 that in your version the final section is now commented out. On mine it isnt (must have changed in one of your recent updates). Is there any reason for this part to be commented out the code?

```
#custom_component:
#  - lambda: |-
#      auto stream_server = new StreamServerComponent(id(uart_bus));
#      stream_server->set_port(10077);
#      return {stream_server};
```

**Comment by EyalRotem** [comment] 2023-05-08 07:45
> ```
> #custom_component:
> #  - lambda: |-
> #      auto stream_server = new StreamServerComponent(id(uart_bus));
> #      stream_server->set_port(10077);
> #      return {stream_server};
> ```

I think it has to do with an imported library he is using on the newer version.
I think it safe to just updated to his latest version as it is.

**Comment by HumanSkunk** [comment] 2023-05-08 07:50
> > ```
> > #custom_component:
> > #  - lambda: |-
> > #      auto stream_server = new StreamServerComponent(id(uart_bus));
> > #      stream_server->set_port(10077);
> > #      return {stream_server};
> > ```
> 
> 
> I think it has to do with an imported library he is using on the newer version.
> I think it safe to just updated to his latest version as it is.

In any of debugging states did you power cycle the actual D1 connected to the Panel? I thought that a recompile would do the same thing as a power cycle as it does restart it however this didnt resolve it. Looking back up through the comments I see there is a suggestion to change some files, but it seems that yours worked without those changes? Can you confirm what changes if at any you made? I really want to get this working, doing a full restore takes ages!

**Comment by EyalRotem** [comment] 2023-05-08 07:58
At the end, I changed nothing except esphome versions and restarts 🤷🏼‍♂️
And now fully updated, no issues.

didn’t power cycle the d1mini since it’s inside the panel rigged to the battery and stuff

**Comment by konradwalsh** [comment] 2023-05-08 08:01
Just chiming in..
I had messed with some files but reverted to originals and like @EyalRotem says

Updated ESPHOME
Updated the board files
Power cycled the board using the device restart button inside HA
FULL homeassistant restart

and it worked fine and stable since

**Comment by HumanSkunk** [comment] 2023-05-08 08:04
@EyalRotem Ok thanks. I thought so when I was reading through. I will look to update again later this afternoon or in the coming days and upload my log files as that may point to an underlying issue which to now seems to be causing a comms issue.

@konradwalsh noted I will try the order you suggested as well. Will mix in a restart both software and hard power as well.

**Comment by davesmeghead** [comment] 2023-05-08 08:19
By using the external library by oxan that is referenced like this in the ESPHome yaml file
```
external_components:
  - source: github://oxan/esphome-stream-server
```
It is no longer necessary to reference it as a lambda custom component so this is in the yaml instead, using the oxan serial component
```
stream_server:
  id: my_stream
  uart_id: uart_bus_visonic
  port: !secret network_port
```
If you keep the following in the yaml file
```
button:
  - platform: restart
    name: "${plug_name} Restart"
```
As @konradwalsh says, then you get a button entity in Home Assistant called this: ```button.visonicinterface_restart```
By going in to HA Developer Tools --> States and filtering on this you should find it.  If you then click on the "I" More Info selection next to its name your should be able to trigger the button that will restart the Wemos in your alarm panel.  It's almost the same as a power cycle. Although a recompile and install from the ESPHome web interface also restarts the Wemos.

@HumanSkunk if you get the chance then upload a log file and I'll take a look through.

**Comment by HumanSkunk** [comment] 2023-05-08 08:40
Apologies for slightly derailing the current topic, so I decided to update my esphome config to better reflect known good however it now wont compile with the new changes. It gets all the way through the process after downloading all the files etc but then just errors. I have attached both the log file from the compile and my config as there isnt any formatting errors as that would have failed before the compile command. It seems to relate to this repeated message:

```multiple definition of `_ZN21StreamServerComponent1```

Error log for compile - [logs_alarm_interface.txt](https://github.com/davesmeghead/visonic/files/11419377/logs_alarm_interface.txt)

config file (note I have added the bead rate to my secrets file) - [alarm_panel.txt](https://github.com/davesmeghead/visonic/files/11419431/alarm_panel.txt)

**Comment by davesmeghead** [comment] 2023-05-08 09:20
Did you perform "Clean Build Files" first?  I think you either have 2 different versions of the same library or perhaps the oxan library and the old one still in place. So you have ".o" object files for more than 1 and so there's multiple definitions.

**Comment by HumanSkunk** [comment] 2023-05-08 09:41
Yes I tried cleaning the build files but seemed to have no impact. I think part of the issue is the fact I repurposed the board from another project and some of the older references are still there. I have now manually deleted all those files and reconfigured everything from scratch so I am now back to where I was pre add-on update with it all working with the alarm. Will try the update of the add-on later today and report back.

**Comment by HumanSkunk** [comment] 2023-05-08 18:28
Apologies for the next silly question but what am I doing wrong when it comes to collecting the right logs needed for debugging?

I added this to my config:

```logger:
  default: error
  logs:
    custom_components.visonic: debug
    pyvisonic: debug
    custom_components.visonic.pyvisonic: debug
    custom_components.visonic.alarm_control_panel: debug
    custom_components.visonic.binary_sensor: debug
    custom_components.visonic.switch: debug
    custom_components.visonic.client: debug
    custom_components.visonic.config_flow: debug
    custom_components.visonic.create_schema: debug
    custom_components.visonic.select: debug
    custom_components.visonic.__init__: debug
```

And then restarted. I then went into the log within the system settings and clicked download. When I opened it it does not contain anywhere the same level of detail as @EyalRotem in an earlier post. The only entries listed in my log file related to Visonic are pasted below:

```2023-05-08 19:13:44.999 DEBUG (MainThread) [custom_components.visonic.pyvisonic] Initialising Protocol - Protocol Version 1.0.19.0
2023-05-08 19:13:45.007 DEBUG (MainThread) [custom_components.visonic.client] Initialising Client - Version 0.8.4.1
2023-05-08 19:13:45.013 INFO (MainThread) [custom_components.visonic] Starting Visonic Component
2023-05-08 19:13:45.077 DEBUG (MainThread) [custom_components.visonic] ************* create connection here **************
2023-05-08 19:13:45.077 INFO (MainThread) [custom_components.visonic] Starting Visonic with entry id=0261fdcfe0fda7c74307d42aea202692 configured panels=1
2023-05-08 19:13:45.077 DEBUG (MainThread) [custom_components.visonic] Panel Ident set up: panelident = 3   next auto panelident = 4
2023-05-08 19:13:45.077 INFO (MainThread) [custom_components.visonic.client] Exclude sensor list = []     Exclude x10 list = []
2023-05-08 19:13:45.078 DEBUG (MainThread) [custom_components.visonic] Setting client ID for entry id 0261fdcfe0fda7c74307d42aea202692```

I have no updated to the latest version of HA and ESPHome and it worked fine. Soon as I updated the Visonic Add-On it all went unresponsive. No amount of restarting/rebooting HA and power cycling the Wemos did anything. I am now restoring back to the backup I made before updating the Add-On.

I do not get any errors reported in HA saying it had issue communicating with the panel which I have had before when making other changes and restarting HA.

**Comment by davesmeghead** [comment] 2023-05-08 21:25
This might be obvious and you may have missed it accidentally, do you have "logger:" in there like this
```
logger:
  default: error
  logs:
    custom_components.visonic: debug
```
It's [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) on the wiki.
You only need ```custom_components.visonic: debug``` and nothing else as it then takes all output from all files in the integration to the log file. 
I also noticed that you only have 1 panel but it has ident number 3

**Comment by HumanSkunk** [comment] 2023-05-10 10:11
@davesmeghead thanks and yes those are added to my config. With a working config:
- Add-On version: 0.8.2.4
- HA Version: 2023.5.2
- ESP Home Version: 2023.4.4

I see all these debug logs with things 'working correctly'  [addonworking100523.log](https://github.com/davesmeghead/visonic/files/11440596/addonworking100523.log)

As soon as I update to the lastest Add-On Version: 0.8.4.1 then I get the same set of log messages listed above and that is it, from that point on the panel is unresponsive through HA. No amount of restarts/reboots makes a difference and the log file shows the same 7 events.  [addonnotworking100523.log](https://github.com/davesmeghead/visonic/files/11440599/addonnotworking100523.log). I dont understand why there are no more logs here in this state when there should be a load of connection failure messages, it is almost like the connection just terminates with no error.

Restoring back to a version I know works brings everything back to life and comms are back to normal.

You mentioned about it appearing as Panel 3. Yes I am not sure what went on here but I had a couple of very initial teething issues when connecting it all for the very first time last year and each time the setup failed when I started it again it updated the ID for the panel. I have just renamed it in my dashboard but all the integrations point to a panel 3.

I guess the final option I can try is completely removing the integration/addon and adding it back in and setting it all up from scratch again?

**Comment by davesmeghead** [comment] 2023-05-10 21:56
OK try this, get a command prompt on the HA device.
```
python -m site
```
This shows you the content of sys.path
Look in sys.path for the site packages directory, on mine it looks like this
```
sys.path = [                                                                                   
    '/config',                                                                                 
    '/usr/local/lib/python310.zip',                                                            
    '/usr/local/lib/python3.10',                                                               
    '/usr/local/lib/python3.10/lib-dynload',                                                   
    '/usr/local/lib/python3.10/site-packages',                                                 
    '/usr/src/homeassistant',                                                                  
] 
```
Then type (replace the site packages directory with yours)
```
ls -l /usr/local/lib/python3.10/site-packages/ | grep pyserial
```
On mine this results in 
```
drwxr-xr-x    1 root     root           188 May  5 20:34 pyserial-3.5.dist-info                
drwxr-xr-x    1 root     root           122 May  5 20:35 pyserial_asyncio-0.6.dist-info 
```
So I know that release 0.6 of pyserial_asyncio is installed on my system. 
The concern I have is that it is not backwards compatible with release 0.4

As I said, try removing the integration altogether (if you know how then also manually delete it from the HA ".storage" files) and then installing it again from HACS.

**Comment by HumanSkunk** [comment] 2023-05-11 16:21
Really am not sure if I am using the terminal right here, but commands like that just dont seem to with with HAOS. "python: command not found".
I did try a more verbose grep, and looking in folders where python could be installed and all either contain nothing or no python folder.

I will look to reinstall the add on when I next get local access to the system as I cant remember half the configuration settings when installing the add-on. Will also turn on debug logging and see what I get and will post it.

**Comment by davesmeghead** [comment] 2023-05-13 13:16
The only thing that I can tell from what you've shown me is that the installation itself is either corrupted or there's a mix up of versions somewhere i.e. a mix of .py files from different versions.

**Comment by isablend** [comment] 2023-05-17 12:04
Sorry for the delay in responding from my earlier post (life got in the way), I too am affected by this issue.   I've taken into account what has been said since my last post and so from a working environment (HA - 2023.5.2, ESPHome - 2023.4.4 and Visonic - 0.8.3.0) I upgrade HA to 2023.5.3 and ESPHome to 2023.5.0 but with no re-compile of code on the the D1mini (2023.3.2).   Integration still working.

I then upgraded the integration to 0.8.4.1 and it stops communicating with the panel.  I did take logs before both of these events, but unfortunately because I ended up having to do a full restore from backup, it overwrote the logs.   I can do that again if necessary, but first I want to explain that with the integration not working I took to remove the integration (including the visonic directory in the custom_components directory).  I re-started HA after each of these events with no re-starting of the communication.

I then re-installed the integration manually to ensure the code base from github of the integration was fully installed (with re-start of HA).   Again no change to communication.   As per @HumanSkunk I'm not able to run the commands as commend prompt because they are not available via the command prompt from the Terminal integration (only command prompt I can get).

**Comment by isablend** [comment] 2023-05-17 13:13
ok, one further update.   I've restored back to my base environment (HA - 2023.5.2, ESPHome - 2023.4.4 and Visonic - 0.8.3.0).   I then upgraded to HA to 2023.5.3 and ESPHome to 2023.5.0.   All working.   I then installed the ESPHome upgrade to the D1mini and the integration stops working, without upgrading the integration itself so still on 0.8.3.0.    So for what its worth it looks like the issue is with ESPHome.   Not sure how to solve it, but...

I have the log file from the point at which it stopped where can i post it?

**Comment by EyalRotem** [comment] 2023-05-17 13:15
Pastebin should be fine

**Comment by isablend** [comment] 2023-05-17 13:17
sorry going to appear a bit thick here... where do i find pastebin?

**Comment by isablend** [comment] 2023-05-17 14:49
doesn't work, got a size exceeded message and no URL

**Comment by davesmeghead** [comment] 2023-05-17 18:02
I have ESPHome v2023.5.0 and HA 2023.5.3  i.e. the same as @isablend

I have tried it with my current Visonic Integration version (which I haven't released to you all yet) and it works
I have restored the Visonic Integration version back to 0.8.3.0 and it works

The only thing that is different in my ESPHome system is that I'm trying it with encryption, I've attached the visonic.yaml file that I am currently using (as a zip file).
[visonic.zip](https://github.com/davesmeghead/visonic/files/11501217/visonic.zip)

The important change I made for encryption is here in the visonic.yaml file
```
# Enable Home Assistant API
api:
#  password: !secret device_password
  encryption:
    key: !secret esphome_encrypt
  services:
```

You will need to add this to your secrets.yaml
```
# go here to create a random key https://esphome.io/components/api.html
esphome_encrypt: <Put Random Key Here>
```
As it says, create a random key and put it in the secrets.yaml file. It's under the "Configuration Variables", "encryption" and "key". Then you'll need the same key in the ESPHome Integration so you will need to delete the integration from HA and create it again but using the key this time.

Let me know if this helps please

**Comment by davesmeghead** [comment] 2023-05-17 18:06
As an afterthought...
It's interesting that you're using 0.8.3.0 as that's the first release to use the updated ```pyserial_asyncio``` library at version 0.6.
So that rules out that as a potential problem.

**Comment by isablend** [comment] 2023-05-18 11:42
@davesmeghead I also have the encryption line in my esphome file for the D1min.  The only other difference I could see was the header, so you had;

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini

I had;
esphome:
  name: ${plug_name}
esp8266: 
  board: d1_mini

I've updated to reflect your position, re-compiled from clean and re-installed the D1mini, but no impact.   I've taken log files pre and post integration update only (after it dosn't work), but they only seem to show that there is no attempt to connect; ie. I'm missing the lines
2023-05-18 12:16:21.852 DEBUG (MainThread) [custom_components.visonic.client] ........... attempting connection
2023-05-18 12:16:21.852 DEBUG (MainThread) [custom_components.visonic.client] Visonic Connection Device Type is ethernet {<PyConfiguration.DownloadCode: 0>: 'AAAA', <PyConfiguration.ForceStandard: 9>: False, <PyConfiguration.ForceAutoEnroll: 1>: True, <PyConfiguration.AutoSyncTime: 2>: True, <PyConfiguration.PluginLanguage: 3>: 'EN', <PyConfiguration.MotionOffDelay: 4>: 120.0, <PyConfiguration.SirenTriggerList: 5>: ['intruder'], <PyConfiguration.B0_Enable: 6>: False, <PyConfiguration.B0_Min_Interval_Time: 7>: 5, <PyConfiguration.B0_Max_Wait_Time: 8>: 30}
2023-05-18 12:16:21.852 DEBUG (MainThread) [custom_components.visonic.pyvisonic] Setting TCP socket Options

**Comment by isablend** [comment] 2023-05-18 12:55
Pre- update: https://pastebin.com/VsRU4Xb9
Post-update: https://pastebin.com/hx8hdbnm

**Comment by EyalRotem** [comment] 2023-05-18 13:16
Not sure, but I think k the post update doesn’t have the logger set to :
https://github.com/davesmeghead/visonic/wiki#logger-settings

Which might make it harder to decipher.z

**Comment by isablend** [comment] 2023-05-18 13:28
once more unto the breach...I've re-done the restore and then the update, underneath is the logger output...
https://pastebin.com/wXAaF50F

**Comment by davesmeghead** [comment] 2023-05-18 21:28
Hi @isablend 
With the Post Update and latest release can you try:
- restart HA and give it time to fail, a few minutes at least
- go to the Integrations page, click the 3 vertical dots and then Reload. 

Can you show me the log extract for this time period please.

**Comment by isablend** [comment] 2023-05-19 08:17
@davesmeghead
currently on 0.8.3.0, then per instruction, upgraded integration, restart, reload integration.   Attached logs
https://pastebin.com/5tGQ9xNa

**Comment by HumanSkunk** [comment] 2023-05-19 09:15
So an update from me. Had some free time this morning so decided to go down the upgrade path once again to try and complete reinstall again but this time capture logs. However upon redoing everything it connected without error and I can control the alarm from within HA.

Steps I took:

1. Updated everything in HA before changing anything with the integration. HA Core at 2023.5.3, ESPHome at 2023.5.1 and the build on the D1 also at that version.
2. I removed the integration
3. I deleted the integration from within HACS
4. I used File Editor add-on to confirm everything had been removed
5. Restarted HA (not a reboot)
6. Reinstalled the Integration through HACS
7. Restarted HA (not a reboot)
8. Configured the integration through HA
9. All connected fine.

The only difference between this as the last time I ran through was that ESPHome was then over version 2023.5.0. Perhaps they changed something with how the boards communicated and then reverted. I cant see anything in the release notes indicating that. If something didnt change in ESPHome then I really cant explain what was different. I can confirm I followed the exact same steps last week and I got nothing back from the board. Could argue I perhaps fat fingered something... but either way it's now fully working. @isablend perhaps try the latest ESPHome version and try again?

**Comment by isablend** [comment] 2023-05-19 10:03
@HumanSkunk @davesmeghead 
I followed the steps laid out by @HumanSkunk and still no difference for me.
I am getting the Notification
![image](https://github.com/davesmeghead/visonic/assets/43060402/097151ae-19c5-4ddb-bc79-28e295dc0fa9)

The logs are here;
https://pastebin.com/DJDpBgzL

Interestingly it looks as though the integration is, despite being loaded being ignored (from what I can read).

**Comment by isablend** [comment] 2023-05-19 10:18
One last thing.   I had a look at the 'Download Diagnostics' option on the integration and get the following;
    "visonic": {
      "version": "0.8.3.0",
      "requirements": [
        "pyserial_asyncio==0.6"
      ]
    },

and that is despite removing the integration and from HACS and re-installing.   That doesn't strike me as right?

**Comment by HumanSkunk** [comment] 2023-05-19 12:59
When you are removing it from HACS are you sure it has removed everything? I know it should have but sometimes HACS left some files that I also had to manually delete. After you have removed it I would just verify that all the old files have gone from within the custom_components folder that is in the same folder as your configuration.yaml.

Also as a complete clean when you reinstalled your ESPHome configuration to the board did you also remove those files that are often left behind? they are in the esphome folder in the same master folder as above. there were also some files within a hidden folder .esphome as well. Granted deleting the above in the ESPHome folder didnt solve the issue for me, but perhaps a combination of all the things above did. Does make it more annoying to work out what the actual problem was in the first place...

This may not be in anyway linked to the issue but could be worth a try, especially when its reporting to be at a different version.

**Comment by davesmeghead** [comment] 2023-05-19 15:45
For this...
```
Hi @isablend
With the Post Update and latest release can you try:

    restart HA and give it time to fail, a few minutes at least
    go to the Integrations page, click the 3 vertical dots and then Reload.

Can you show me the log extract for this time period please.
```
You used the old integration version, I asked you to do this with the **latest release**
Can you do it again with the latest release please

**Comment by davesmeghead** [comment] 2023-05-19 15:50
When you see this
```
One last thing. I had a look at the 'Download Diagnostics' option on the integration and get the following;
"visonic": {
"version": "0.8.3.0",
```
It's probably my fault, I didn't update the version code in the manifest.json file and it still says 0.8.3.0
I've just updated manifest.json on guthub

**Comment by isablend** [comment] 2023-05-24 14:22
@davesmeghead I'm back and decided to go back and re-check each activity as its done.   From within HACS I applied the update it was advertising.   A re-start is then required.   However before I did that I decided to check to see what was in the custom_components directory.   All the files are date and timestamped as you would expect with todays date and time.   However based on your comment about me failing to update the integration before re-starting I thought I'd check the manifest file you mentioned.   This does not include the update that your github file is showing.   I.e. it still shows 0.8.3.0 which implies that whatever HACS is doing it may not be doing the update I thought it was doing.   I'm going to manually download all the files and see what impact this has and will report back with findings.

**Comment by EyalRotem** [comment] 2023-05-24 14:41
Dave said 2 comments ago that the manifest file wasn’t updated at his fault, and if I understand correctly-it affects logging but not how the integration works - as most of us have no issues🤗

the file is only updated on GitHub since the latest iteration isn’t released yet

**Comment by isablend** [comment] 2023-05-24 15:31
That's why I mentioned it.   I updated the files using HACS and yet the file stored where the updated HACS file should be had the old information in it, not the new.   So not within HA, but the file which should then be used as the basis for HA logging.   That tells me that there may be in issue in the delivery of files from Github with HACS not with the integration itself.

**Comment by isablend** [comment] 2023-05-25 13:29
ok, one further update.
I've been able to consistently go back to a backup of the system including integration 0.8.3.0 throughout this issue.   When ever I've got to a position of stalemate I have reverted back to that backup and all works.
I've manually forced the individual files updates by downloading each file from Github to ensure that that code is in place where it should be.
I've today actually achieved the upgrade from 0.8.3.0 to 0.8.4.1 but that it required I remove the integration and then re-install and then that a restart of the alarm panel is required before it will communicate.   Bottom line it is now working, can't say I understand why.

**Comment by davesmeghead** [comment] 2023-05-25 18:19
I'm really happy that you've got it working.  It shows me that it's not the Integration at fault but has been a problem with either HA itself or with HACS doing the upgrade.  Although you should not have needed to restart the alarm panel.
D

**Comment by davesmeghead** [comment] 2023-07-02 09:52
I'll close this issue but any further problems then create a new issue and refer back to this one if appropriate.

**Closed by davesmeghead** 2023-07-02 09:52 UTC
